### ISSUE TITLE
Code reorganization

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-storage#5]
So now that the barebones work, the repo needs to be reorganized so that we can scale it better! This should be done by the end of the day, but for clarity's sake here's the plan:

- Refactor the storage package into a domain package and implementation package. Separating the storage implementation from the interfaces and structs that it implements will allow more flexibility when we deal with key generation, adding more platforms, using other storage mediums (e.g. a decentralized store instead of stormDB).

- Adding support for Golang modules, to make this friendlier to the open source community and manage dependencies better. 

- Properly using Git flow! Screwed up the separation between master and develop branches (i.e. did not have a develop branch, oops!)

- Add test files!

**Comment by faddat** [comment]
Awesome!

**Comment by guylepage3** [comment]
Moving this issue to [Sprint 6](https://github.com/orgs/universelabs/projects/7)

**Comment by guylepage3** [comment]
@itamarreif is this complete? Or can we push  this to Sprint 7?

**Comment by itamarreif** [comment]
yep this is complete!
