### ISSUE TITLE
Storage status and future steps

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-storage#6]
Since we've reached a point where the storage part is functioning at a minimal level, let me summarize a bit. In the grand scheme of having a mobile device and a storage node which would communicate through a web interface, this repo represents the storage node. It currently supports:

- Storing keys using stormDB, which is sort of a query layer on top of an embedded boltDB instance, which is an in-memory key-value store.
- A REST API that allows the webapp to perform CRUD operations on keys as well as request specific keys based on platform, id, and other tags. 

The repo is currently in the process of being refactored to a more modular layout that will support future features and growth (see issue #5). Additionally, we are using mock structs for wallets at the moment (wallet.go), rather than functioning wallets for the platforms. @faddat is currently working on implementing this for Blockstack, BTC, and ETH.

In the future, the node will be only handle storage, i.e. will hold not representation of the keys as they will be encrypted. As such, the REST API will be reworked and authentication and encryption will be added for example. Moreover, we might consider implementing a decentralized storage layer in place of the embedded key-value store for users who which to have backup, and the storm package could be replaced by an implementation using a platform such as Storj or IPFS+Filecoin, for example.

**Comment by guylepage3** [comment]
This is perfect. Thank you @itamarreif.

**Comment by guylepage3** [comment]
Closing issue. Thanks for the update.
